module.exports.VoicevoxCore = exports.VoicevoxCore = require("bindings")("voicevox");
var VoicevoxResultCode;
(function (VoicevoxResultCode) {
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_OK"] = 0] = "VOICEVOX_RESULT_OK";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_NOT_LOADED_OPENJTALK_DICT_ERROR"] = 1] = "VOICEVOX_RESULT_NOT_LOADED_OPENJTALK_DICT_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_GET_SUPPORTED_DEVICES_ERROR"] = 3] = "VOICEVOX_RESULT_GET_SUPPORTED_DEVICES_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_GPU_SUPPORT_ERROR"] = 4] = "VOICEVOX_RESULT_GPU_SUPPORT_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_STYLE_NOT_FOUND_ERROR"] = 6] = "VOICEVOX_RESULT_STYLE_NOT_FOUND_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_MODEL_NOT_FOUND_ERROR"] = 7] = "VOICEVOX_RESULT_MODEL_NOT_FOUND_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_INFERENCE_ERROR"] = 8] = "VOICEVOX_RESULT_INFERENCE_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_EXTRACT_FULL_CONTEXT_LABEL_ERROR"] = 11] = "VOICEVOX_RESULT_EXTRACT_FULL_CONTEXT_LABEL_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_INVALID_UTF8_INPUT_ERROR"] = 12] = "VOICEVOX_RESULT_INVALID_UTF8_INPUT_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_PARSE_KANA_ERROR"] = 13] = "VOICEVOX_RESULT_PARSE_KANA_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_INVALID_AUDIO_QUERY_ERROR"] = 14] = "VOICEVOX_RESULT_INVALID_AUDIO_QUERY_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_INVALID_ACCENT_PHRASE_ERROR"] = 15] = "VOICEVOX_RESULT_INVALID_ACCENT_PHRASE_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_OPEN_ZIP_FILE_ERROR"] = 16] = "VOICEVOX_RESULT_OPEN_ZIP_FILE_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_READ_ZIP_ENTRY_ERROR"] = 17] = "VOICEVOX_RESULT_READ_ZIP_ENTRY_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_MODEL_ALREADY_LOADED_ERROR"] = 18] = "VOICEVOX_RESULT_MODEL_ALREADY_LOADED_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_STYLE_ALREADY_LOADED_ERROR"] = 26] = "VOICEVOX_RESULT_STYLE_ALREADY_LOADED_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_INVALID_MODEL_DATA_ERROR"] = 27] = "VOICEVOX_RESULT_INVALID_MODEL_DATA_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_LOAD_USER_DICT_ERROR"] = 20] = "VOICEVOX_RESULT_LOAD_USER_DICT_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_SAVE_USER_DICT_ERROR"] = 21] = "VOICEVOX_RESULT_SAVE_USER_DICT_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_USER_DICT_WORD_NOT_FOUND_ERROR"] = 22] = "VOICEVOX_RESULT_USER_DICT_WORD_NOT_FOUND_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_USE_USER_DICT_ERROR"] = 23] = "VOICEVOX_RESULT_USE_USER_DICT_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_INVALID_USER_DICT_WORD_ERROR"] = 24] = "VOICEVOX_RESULT_INVALID_USER_DICT_WORD_ERROR";
    VoicevoxResultCode[VoicevoxResultCode["VOICEVOX_RESULT_INVALID_UUID_ERROR"] = 25] = "VOICEVOX_RESULT_INVALID_UUID_ERROR";
})(VoicevoxResultCode || (exports.VoicevoxResultCode = VoicevoxResultCode = {}));
var VoicevoxAccelerationMode;
(function (VoicevoxAccelerationMode) {
    VoicevoxAccelerationMode[VoicevoxAccelerationMode["VOICEVOX_ACCELERATION_MODE_AUTO"] = 0] = "VOICEVOX_ACCELERATION_MODE_AUTO";
    VoicevoxAccelerationMode[VoicevoxAccelerationMode["VOICEVOX_ACCELERATION_MODE_CPU"] = 1] = "VOICEVOX_ACCELERATION_MODE_CPU";
    VoicevoxAccelerationMode[VoicevoxAccelerationMode["VOICEVOX_ACCELERATION_MODE_GPU"] = 2] = "VOICEVOX_ACCELERATION_MODE_GPU";
})(VoicevoxAccelerationMode || (exports.VoicevoxAccelerationMode = VoicevoxAccelerationMode = {}));
var VoicevoxUserDictWordType;
(function (VoicevoxUserDictWordType) {
    VoicevoxUserDictWordType[VoicevoxUserDictWordType["VOICEVOX_USER_DICT_WORD_TYPE_PROPER_NOUN"] = 0] = "VOICEVOX_USER_DICT_WORD_TYPE_PROPER_NOUN";
    VoicevoxUserDictWordType[VoicevoxUserDictWordType["VOICEVOX_USER_DICT_WORD_TYPE_COMMON_NOUN"] = 1] = "VOICEVOX_USER_DICT_WORD_TYPE_COMMON_NOUN";
    VoicevoxUserDictWordType[VoicevoxUserDictWordType["VOICEVOX_USER_DICT_WORD_TYPE_VERB"] = 2] = "VOICEVOX_USER_DICT_WORD_TYPE_VERB";
    VoicevoxUserDictWordType[VoicevoxUserDictWordType["VOICEVOX_USER_DICT_WORD_TYPE_ADJECTIVE"] = 3] = "VOICEVOX_USER_DICT_WORD_TYPE_ADJECTIVE";
    VoicevoxUserDictWordType[VoicevoxUserDictWordType["VOICEVOX_USER_DICT_WORD_TYPE_SUFFIX"] = 4] = "VOICEVOX_USER_DICT_WORD_TYPE_SUFFIX";
})(VoicevoxUserDictWordType || (exports.VoicevoxUserDictWordType = VoicevoxUserDictWordType = {}));
